# Internal note
# To test this workflow:
# 1. Copy it to .github/workflows
# 2. Add a working-dir of examples/attribute-targeting to the Update FLag Definitions step
# 3. Remove the main branch restriction of on:push:
# 4. Add URL_TO_KV and DENO_KV_ACCESS_TOKEN as environment secrets

name: Update Flag Definitions in KV

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: flagDefinitions
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba # v1.1.4
        with:
          deno-version: "1.43.5"

      - name: Update Flag Definitions
        env:
          URL_TO_KV: ${{ secrets.URL_TO_KV }}
          DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_KV_ACCESS_TOKEN }}
        run: |
          deno run --unstable-kv --allow-read=flags.json --allow-env=URL_TO_KV,DENO_KV_ACCESS_TOKEN --allow-net updateFlagDefinitionsInKv.ts
